
name: Seleniu IDE CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chome-stable
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run test
      env:
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: dotnet test --verbosity normal
